# Generated by Django 4.0.3 on 2022-03-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Address', models.TextField(max_length=50)),
            ],
        ),
    ]
