# Generated by Django 4.0.3 on 2022-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_information_address_alter_information_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
