# Generated by Django 4.0.3 on 2022-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_education_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='College',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='Specialty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(),
        ),
    ]
