# Generated by Django 4.0.3 on 2022-03-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_experience_responsibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='responsibility',
        ),
        migrations.DeleteModel(
            name='experience',
        ),
        migrations.DeleteModel(
            name='responsibility',
        ),
    ]
