# Generated by Django 4.0.3 on 2022-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_portofolio_alter_experience_yearend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='Picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='Type',
            field=models.CharField(choices=[('الكل', 'الكل'), ('الكتب', 'الكتب'), ('الصور', 'الصور'), ('فيديوهات', 'فيديوهات'), ('أفلام', 'أفلام'), ('تصاميم', 'تصاميم')], default='الكل', max_length=50),
        ),
    ]
