# Generated by Django 4.0.3 on 2022-03-30 14:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0012_alter_portofolio_picture_alter_portofolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='Type',
            field=models.CharField(choices=[('الكل', 'all'), ('الكتب', 'book'), ('الصور', 'picture'), ('فيديوهات', 'videos'), ('أفلام', 'movies'), ('تصاميم', 'design')], default='All', max_length=50),
        ),
    ]
