# Generated by Django 4.0.3 on 2022-03-30 15:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0013_alter_experience_description_alter_portofolio_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=100)),
                ('Blog_thumbnail', models.ImageField(upload_to='Blog_thumbnail')),
                ('Blog_category', models.CharField(max_length=10)),
                ('Blog_date', models.DateField(auto_now_add=True)),
                ('Blog_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
