# Generated by Django 4.0.3 on 2022-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_blog_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_thumbnail',
            field=models.ImageField(upload_to='Blogthumbnail/'),
        ),
    ]
