# Generated by Django 4.0.3 on 2022-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0015_alter_blog_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Description',
            field=models.CharField(default='من أنا ؟', max_length=255),
        ),
        migrations.AddField(
            model_name='information',
            name='image_about',
            field=models.ImageField(default='default.jpg', upload_to='Images About/'),
        ),
    ]
