# Generated by Django 4.0.3 on 2022-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0016_information_description_information_image_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Description',
            field=models.TextField(),
        ),
    ]
