# Generated by Django 4.0.3 on 2022-04-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_portofolio_download_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portofolio',
            old_name='Type',
            new_name='نوع',
        ),
    ]
