# Generated by Django 4.0.3 on 2022-04-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_rename_type_portofolio_نوع'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portofolio',
            old_name='نوع',
            new_name='Type',
        ),
    ]
